# Generated by Django 5.2.1 on 2025-05-28 13:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsIssueNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_code', models.CharField(max_length=50, unique=True, verbose_name='Mã phiếu xuất')),
                ('issued_to', models.CharField(max_length=200, verbose_name='Xuất cho (Công trình/Ai)')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Lý do xuất')),
                ('issue_date', models.DateField(verbose_name='Ngày xuất')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Phiếu xuất kho',
                'verbose_name_plural': 'Các phiếu xuất kho',
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_code', models.CharField(max_length=50, unique=True, verbose_name='Mã phiếu nhập')),
                ('receipt_date', models.DateField(verbose_name='Ngày nhập')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Phiếu nhập kho',
                'verbose_name_plural': 'Các phiếu nhập kho',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã sản phẩm')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('quantity_on_hand', models.IntegerField(default=0, verbose_name='Số lượng tồn kho')),
            ],
            options={
                'verbose_name': 'Hàng hóa',
                'verbose_name_plural': 'Các mặt hàng',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên loại hàng')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Loại hàng hóa',
                'verbose_name_plural': 'Các loại hàng hóa',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên nhà cung cấp')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Người liên hệ')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
            ],
            options={
                'verbose_name': 'Nhà cung cấp',
                'verbose_name_plural': 'Các nhà cung cấp',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tên đơn vị')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Đơn vị tính',
                'verbose_name_plural': 'Các đơn vị tính',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tendangnhap', models.CharField(max_length=100, unique=True, verbose_name='Tên đăng nhập')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('ho', models.CharField(max_length=100, verbose_name='Họ')),
                ('ten', models.CharField(max_length=100, verbose_name='Tên')),
                ('matkhau_hashed', models.CharField(max_length=128, verbose_name='Mật khẩu (đã băm)')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Là quản trị viên kho')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tham gia')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Đăng nhập lần cuối')),
            ],
            options={
                'verbose_name': 'Tài khoản người dùng (Tùy chỉnh)',
                'verbose_name_plural': 'Các tài khoản người dùng (Tùy chỉnh)',
                'ordering': ['tendangnhap'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Số lượng nhập')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Đơn giá nhập')),
                ('receipt_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.goodsreceiptnote', verbose_name='Phiếu nhập')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Chi tiết phiếu nhập',
                'verbose_name_plural': 'Các chi tiết phiếu nhập',
            },
        ),
        migrations.CreateModel(
            name='GoodsIssueNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Số lượng xuất')),
                ('issue_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.goodsissuenote', verbose_name='Phiếu xuất')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Chi tiết phiếu xuất',
                'verbose_name_plural': 'Các chi tiết phiếu xuất',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.productcategory', verbose_name='Loại hàng'),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.supplier', verbose_name='Nhà cung cấp'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.unit', verbose_name='Đơn vị tính'),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='staff_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.useraccount', verbose_name='Nhân viên thực hiện'),
        ),
        migrations.AddField(
            model_name='goodsissuenote',
            name='staff_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.useraccount', verbose_name='Nhân viên thực hiện'),
        ),
    ]
